-- V6: 创建景区基础信息表
CREATE TABLE `scenic_spots` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '景区ID，主键自增',
    `name` VARCHAR(200) NOT NULL COMMENT '景区名称',
    `level` VARCHAR(20) COMMENT '景区级别，如: A, AA, AAA, AAAA, AAAAA(5A)',
    `introduction` TEXT COMMENT '景区详细介绍',
    `province` VARCHAR(50) NOT NULL COMMENT '所在省份',
    `city` VARCHAR(50) NOT NULL COMMENT '所在城市',
    `district` VARCHAR(50) COMMENT '所在区县',
    `address` VARCHAR(500) NOT NULL COMMENT '详细地址',
    `longitude` DECIMAL(10, 6) COMMENT '经度，用于地图定位',
    `latitude` DECIMAL(10, 6) COMMENT '纬度，用于地图定位',
    `opening_hours` VARCHAR(200) COMMENT '开放时间描述，如: 08:00-18:00',
    `contact_phone` VARCHAR(20) COMMENT '景区联系电话',
    `cover_image` VARCHAR(500) COMMENT '封面图片URL',
    `images` JSON COMMENT '景区图片列表，JSON数组格式',
    `tags` JSON COMMENT '景区标签，JSON数组格式，如: ["自然风光", "文化古迹"]',
    `facilities` JSON COMMENT '景区设施，JSON数组格式，如: ["停车场", "餐厅", "卫生间"]',
    `ticket_info` TEXT COMMENT '门票信息说明',
    `traffic_info` TEXT COMMENT '交通信息说明',
    `notice` TEXT COMMENT '游玩须知',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE-开放, INACTIVE-关闭, MAINTENANCE-维护中',
    `view_count` INT DEFAULT 0 COMMENT '浏览次数',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX `idx_city` (`city`) COMMENT '城市索引',
    INDEX `idx_level` (`level`) COMMENT '景区级别索引',
    INDEX `idx_status` (`status`) COMMENT '状态索引',
    INDEX `idx_province_city` (`province`, `city`) COMMENT '省市联合索引'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '景区基础信息表';
-- 插入测试数据
INSERT INTO `scenic_spots` (
        `name`,
        `level`,
        `introduction`,
        `province`,
        `city`,
        `district`,
        `address`,
        `longitude`,
        `latitude`,
        `opening_hours`,
        `contact_phone`,
        `cover_image`,
        `tags`,
        `facilities`,
        `ticket_info`,
        `traffic_info`,
        `notice`,
        `status`
    )
VALUES (
        '太行山大峡谷',
        'AAAA',
        '太行山大峡谷位于山西省长治市壶关县，是国家AAAA级旅游景区，被誉为"中国最美十大峡谷"之一。峡谷总长约50公里，最高海拔1705米，景区内有八泉峡、红豆峡、黑龙潭等著名景点。',
        '山西省',
        '长治市',
        '壶关县',
        '长治市壶关县桥上乡',
        113.450000,
        36.150000,
        '08:00-18:00',
        '0355-8878000',
        'https://example.com/images/taihang.jpg',
        '["自然风光", "峡谷", "山水", "徒步"]',
        '["停车场", "游客中心", "餐厅", "卫生间", "观光车"]',
        '成人票：120元/人；学生票：60元/人；儿童、老人免票',
        '自驾：长治市区出发，沿S77省道至壶关县，再转县道至景区；公交：长治客运东站乘坐至壶关的班车',
        '1. 请注意安全，遵守景区规定；2. 禁止攀爬未开放区域；3. 保护环境，请勿乱扔垃圾；4. 建议穿着舒适的运动鞋',
        'ACTIVE'
    ),
    (
        '八路军太行纪念馆',
        'AAAA',
        '八路军太行纪念馆位于山西省长治市武乡县，是全国重点文物保护单位、国家AAAA级旅游景区。纪念馆展示了八路军在太行山区的抗战历史，是进行爱国主义教育的重要基地。',
        '山西省',
        '长治市',
        '武乡县',
        '长治市武乡县太行街363号',
        112.860000,
        36.840000,
        '09:00-17:00',
        '0355-6388102',
        'https://example.com/images/balujun.jpg',
        '["红色旅游", "历史文化", "爱国教育"]',
        '["停车场", "游客中心", "纪念品商店", "卫生间"]',
        '免费开放（需凭身份证领取门票）',
        '自驾：长治市区出发，沿G55二广高速至武乡出口；公交：长治客运站乘坐至武乡的班车',
        '1. 参观时请保持安静，尊重历史；2. 禁止在馆内吸烟；3. 爱护文物，请勿触摸展品',
        'ACTIVE'
    ),
    (
        '通天峡景区',
        'AAAA',
        '通天峡景区位于山西省长治市平顺县，是国家AAAA级旅游景区。景区以峡谷、溶洞、瀑布、湖泊为主要特色，有"太行第一峡"之称。主要景点包括通天湖、通天瀑、通天洞等。',
        '山西省',
        '长治市',
        '平顺县',
        '长治市平顺县虹梯关乡',
        113.610000,
        36.200000,
        '08:30-17:30',
        '0355-8700999',
        'https://example.com/images/tongtian.jpg',
        '["自然风光", "峡谷", "瀑布", "溶洞"]',
        '["停车场", "游客中心", "餐厅", "卫生间", "索道", "游船"]',
        '成人票：98元/人；学生票：49元/人；索道、游船另收费',
        '自驾：长治市区出发，沿S76省道至平顺县，再转县道至景区',
        '1. 山区天气多变，请备好雨具；2. 乘坐索道、游船请遵守安全规定；3. 注意防滑，雨天谨慎游览',
        'ACTIVE'
    );